### ISSUE TITLE
Add support for Battery Camera video WebRTC streams

### ISSUE THREAD

**Issue by allenporter** [allenporter/python-google-nest-sdm#58]
See [Release Notes](https://developers.google.com/nest/device-access/release-notes?hl=en#september_21_2021) for the new additions to the SDM API.

- See https://developers.google.com/nest/device-access/api/doorbell-battery?hl=en for specifics on battery doorbells which have methods mirroring the existing RTSP methods but for WebRTC
- Expiration looks different. This is interesting from the notes:
```
A WebRTC stream cannot be extended on battery-powered doorbells. If a stream on a doorbell needs to be viewed beyond the initial session length, stop the existing stream and generate a new one.
```
- Need to determine if a particular doorbell supports WebRTC vs RTSP -- unclear how.

**Comment by rgregrowe** [comment]
Hi Allen,
 Just to add to this, the new Nest Outdoor Battery cams are also returning:

  google_nest_sdm.exceptions.ApiException: Error from API: 400: INVALID_ARGUMENT: Command  sdm.devices.commands.CameraLiveStream.GenerateRtspStream not supported.: Bad Request

Since I already have power there, I purchased the additional power cable for it. Not sure if that makes any difference in the streaming ability?

**Comment by allenporter** [comment]
Yes, that is what this bug is tracking. The existing way to get a live stream doesn't work for these cameras.
